/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicMykacashAuthRouteImport } from './routes/api/public/mykacash-auth'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMykacashAuthRoute = ApiPublicMykacashAuthRouteImport.update({
  id: '/api/public/mykacash-auth',
  path: '/api/public/mykacash-auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/api/public/mykacash-auth': typeof ApiPublicMykacashAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/api/public/mykacash-auth': typeof ApiPublicMykacashAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/api/public/mykacash-auth': typeof ApiPublicMykacashAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/crm'
    | '/financeiro'
    | '/integration'
    | '/login'
    | '/api/public/mykacash-auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/crm'
    | '/financeiro'
    | '/integration'
    | '/login'
    | '/api/public/mykacash-auth'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/crm'
    | '/financeiro'
    | '/integration'
    | '/login'
    | '/api/public/mykacash-auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CrmRoute: typeof CrmRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IntegrationRoute: typeof IntegrationRoute
  LoginRoute: typeof LoginRoute
  ApiPublicMykacashAuthRoute: typeof ApiPublicMykacashAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mykacash-auth': {
      id: '/api/public/mykacash-auth'
      path: '/api/public/mykacash-auth'
      fullPath: '/api/public/mykacash-auth'
      preLoaderRoute: typeof ApiPublicMykacashAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CrmRoute: CrmRoute,
  FinanceiroRoute: FinanceiroRoute,
  IntegrationRoute: IntegrationRoute,
  LoginRoute: LoginRoute,
  ApiPublicMykacashAuthRoute: ApiPublicMykacashAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
